/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;

import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Michael Kevin
 */
public class MasterKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form MasterKaryawan
     */
    public MasterKaryawan() {
        initComponents();
        jPanel1.setFocusable(true);
        Login.FrameDragListener frameDragListener = new Login.FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        settingTabel();
    }
    
    public void settingTabel(){
        tabelKaryawan.getTableHeader().setFont(new Font("Berlin Sans FB Demi", Font.BOLD, 14));
        tabelKaryawan.getTableHeader().setOpaque(false);
        tabelKaryawan.getTableHeader().setBackground(new Color(255, 255, 255));
        tabelKaryawan.getTableHeader().setForeground(new Color(0, 0, 0));
        tabelKaryawan.setRowHeight(25);
        tabelKaryawan.setModel(DB.getTabelKaryawan());
        TableColumnModel columnModel = tabelKaryawan.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);
        columnModel.getColumn(1).setPreferredWidth(5);
        columnModel.getColumn(2).setPreferredWidth(3);
        columnModel.getColumn(3).setPreferredWidth(2);
        columnModel.getColumn(4).setPreferredWidth(4);
        columnModel.getColumn(5).setPreferredWidth(50);
    }
    
    public static class FrameDragListener extends MouseAdapter {

        private final JFrame frame;
        private Point mouseDownCompCoords = null;

        public FrameDragListener(JFrame frame) {
            this.frame = frame;
        }

        public void mouseReleased(MouseEvent e) {
            mouseDownCompCoords = null;
        }

        public void mousePressed(MouseEvent e) {
            mouseDownCompCoords = e.getPoint();
        }

        public void mouseDragged(MouseEvent e) {
            Point currCoords = e.getLocationOnScreen();
            frame.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        radManager = new javax.swing.JRadioButton();
        radKasir = new javax.swing.JRadioButton();
        radAktif = new javax.swing.JRadioButton();
        radTidakAktif = new javax.swing.JRadioButton();
        btnMasterKaryawan = new javax.swing.JButton();
        btnMasterKaryawan1 = new javax.swing.JButton();
        btnMasterKaryawan2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(26, 50, 90));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/close.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        tabelKaryawan.setBackground(new java.awt.Color(204, 204, 204));
        tabelKaryawan.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        tabelKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKaryawan.setRowHeight(25);
        tabelKaryawan.setSelectionBackground(new java.awt.Color(0, 239, 173));
        tabelKaryawan.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKaryawan);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Master Karyawan");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Karyawan :");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama :");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username :");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status :");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jabatan :");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(26, 50, 90));
        txtID.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setMargin(new java.awt.Insets(0, 5, 0, 5));

        txtNama.setBackground(new java.awt.Color(26, 50, 90));
        txtNama.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setMargin(new java.awt.Insets(0, 5, 0, 5));

        txtPass.setBackground(new java.awt.Color(26, 50, 90));
        txtPass.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setMargin(new java.awt.Insets(0, 5, 0, 5));

        txtUsername.setBackground(new java.awt.Color(26, 50, 90));
        txtUsername.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setMargin(new java.awt.Insets(0, 5, 0, 5));

        radManager.setBackground(new java.awt.Color(26, 50, 90));
        buttonGroup1.add(radManager);
        radManager.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        radManager.setForeground(new java.awt.Color(255, 255, 255));
        radManager.setText("Manager");

        radKasir.setBackground(new java.awt.Color(26, 50, 90));
        buttonGroup1.add(radKasir);
        radKasir.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        radKasir.setForeground(new java.awt.Color(255, 255, 255));
        radKasir.setText("Kasir");

        radAktif.setBackground(new java.awt.Color(26, 50, 90));
        buttonGroup2.add(radAktif);
        radAktif.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        radAktif.setForeground(new java.awt.Color(255, 255, 255));
        radAktif.setText("Aktif");

        radTidakAktif.setBackground(new java.awt.Color(26, 50, 90));
        buttonGroup2.add(radTidakAktif);
        radTidakAktif.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        radTidakAktif.setForeground(new java.awt.Color(255, 255, 255));
        radTidakAktif.setText("Tidak aktif");

        btnMasterKaryawan.setBackground(new java.awt.Color(0, 239, 173));
        btnMasterKaryawan.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btnMasterKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnMasterKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/insert.png"))); // NOI18N
        btnMasterKaryawan.setText("  Insert");
        btnMasterKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterKaryawanActionPerformed(evt);
            }
        });

        btnMasterKaryawan1.setBackground(new java.awt.Color(0, 239, 173));
        btnMasterKaryawan1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btnMasterKaryawan1.setForeground(new java.awt.Color(255, 255, 255));
        btnMasterKaryawan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/update.png"))); // NOI18N
        btnMasterKaryawan1.setText("  Update");
        btnMasterKaryawan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterKaryawan1ActionPerformed(evt);
            }
        });

        btnMasterKaryawan2.setBackground(new java.awt.Color(255, 102, 102));
        btnMasterKaryawan2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btnMasterKaryawan2.setForeground(new java.awt.Color(255, 255, 255));
        btnMasterKaryawan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/images/delete.png"))); // NOI18N
        btnMasterKaryawan2.setText(" Delete");
        btnMasterKaryawan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterKaryawan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblExit)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID)
                                    .addComponent(txtPass)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(radManager)
                                                .addGap(18, 18, 18)
                                                .addComponent(radKasir))
                                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addComponent(radAktif)
                                        .addGap(18, 18, 18)
                                        .addComponent(radTidakAktif)))
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMasterKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMasterKaryawan1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnMasterKaryawan2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(296, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExit)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(radManager)
                            .addComponent(radKasir))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(radAktif)
                            .addComponent(radTidakAktif)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasterKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMasterKaryawan1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMasterKaryawan2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        FormPenghubung f = new FormPenghubung();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnMasterKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterKaryawanActionPerformed
        MasterKaryawan f = new MasterKaryawan();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMasterKaryawanActionPerformed

    private void btnMasterKaryawan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterKaryawan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasterKaryawan1ActionPerformed

    private void btnMasterKaryawan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterKaryawan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasterKaryawan2ActionPerformed

    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        int idx = tabelKaryawan.getSelectedRow();
        if (idx >= 0 && idx < tabelKaryawan.getRowCount()) {
            txtID.setText(DB.getTabelKaryawan().getValueAt(idx, 0).toString());
            txtNama.setText(DB.getTabelKaryawan().getValueAt(idx, 1).toString());
            txtUsername.setText(DB.getTabelKaryawan().getValueAt(idx, 2).toString());
            txtPass.setText(DB.getTabelKaryawan().getValueAt(idx, 3).toString());
            String status = DB.getTabelKaryawan().getValueAt(idx, 4).toString();
            if (status.equals("Aktif")) {
                radAktif.setSelected(true);
                radTidakAktif.setSelected(false);
            }
            else{
                radAktif.setSelected(false);
                radTidakAktif.setSelected(true);
            }
            String jabatan = DB.getTabelKaryawan().getValueAt(idx, 5).toString();
            if (jabatan.equals("Kasir")) {
                radKasir.setSelected(true);
                radManager.setSelected(false);
            }
            else{
                radKasir.setSelected(false);
                radManager.setSelected(true);
            }
        }
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasterKaryawan;
    private javax.swing.JButton btnMasterKaryawan1;
    private javax.swing.JButton btnMasterKaryawan2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JRadioButton radAktif;
    private javax.swing.JRadioButton radKasir;
    private javax.swing.JRadioButton radManager;
    private javax.swing.JRadioButton radTidakAktif;
    private javax.swing.JTable tabelKaryawan;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
